name: Coverage

on:
  push:
    branches: ['master', '0.5.x']

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/tarpaulin@044a1e5bdace8dd2f727b1af63c1d9a1d3572068 # v0.1
      - uses: codecov/codecov-action@cb218a0977f94755cee8a27ab63232797780f625 # v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1
        with:
          name: code-coverage-report
          path: cobertura.xml
